project_id = "vqlusbhqoalhbfiotdhi"

[api]
enabled = true
port = 54321
schemas = ["public", "storage"]
extra_search_path = ["public"]
max_rows = 1000

[auth]
enable_signup = true
enable_anonymous_sign_ins = false

[functions.create-user]
verify_jwt = true

[functions.delete-user]
verify_jwt = true

[functions.generate-pdf]
verify_jwt = false

[functions.reset-user-password]
verify_jwt = true

[functions.reset-super-admin-password]
verify_jwt = false

[functions.serve-contract-html]
verify_jwt = false
